### ISSUE TITLE
.DS_Store, wat is dat?

### ISSUE THREAD

**Issue by Martbov** [chrispool/gevpro-week2-premasters#1]
Chris, ik heb lokaal in m'n Git map een bestand staan genaamd '.DS_Store'. Enig idee wat dat is? Moet ik die ook adden of kan 'm verwijderen?
![schermafbeelding 2015-02-11 om 11 13 01](https://cloud.githubusercontent.com/assets/10852175/6145152/f92bdbec-b1de-11e4-9241-da7b3a7eb70a.png)

**Comment by chrispool** [comment]
He Mart,
dat is iets dat Mac toevoegt, die moeten we even toevoegen aan gitignore, doe ik zo wel even. Als je dan pulled krijg je die melding niet meer te zien
